# Лабораторна робота №7
## Фінальний проєкт

**Варіант 1 — асистент із базою знань (RAG + Agent).**

Мета: інтегрувати Redis RAG лабораторної 3 та інструменти й пам’ять Agents SDK лабораторної 6 у локальний застосунок. Notebook показує збережені реальні експерименти, перевіряє їхні хеші та виконує новий пошуковий запит. Для нової повної серії використовуйте `python -m src.experiments --force` із каталогу Lab 7.

In [1]:
from pathlib import Path
import sys, json
import pandas as pd
from IPython.display import display
lab = next(p for p in [Path.cwd(), Path.cwd().parent, Path.cwd()/'labs/lab07_final_project'] if (p/'assets/knowledge/manifest.json').exists())
sys.path.insert(0, str(lab))
from src.config import Settings, OUTPUTS
from src.knowledge_base import KnowledgeBase, validate_corpus
from src.agent import connect
from src.experiments import load_batch, experiment_fingerprint
from src.evaluation import summarize
read = lambda name: json.loads((OUTPUTS/name).read_text(encoding='utf-8'))
records = load_batch()
print('Реальні збережені результати, SHA-256 перевірено:', len(records))

C:\Users\Eclipse\PycharmProjects\neural-network-technologies-and-systems\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Реальні збережені результати, SHA-256 перевірено: 15

## 1. Концепція застосунку

Асистент відповідає на питання про власні завершені лабораторні. Джерела — чотири незмінені звіти; модель не отримує еталонні відповіді. Користувач працює через CLI з командами `/help`, `/sources`, `/new`, `/session`, `/exit`.

## 2. Інтегровані попередні лабораторні

| Компонент | Роль |
|---|---|
| Lab 3: LangChain, MiniLM, Redis | Пошук фрагментів звітів |
| Lab 6: OpenAI Agents SDK, function tools, SQLiteSession | Вибір дій та історія діалогу |
| LM Studio | Локальна генерація через Chat Completions |

## 3. Архітектура

```mermaid
flowchart TD
    U[Користувач CLI] --> A[OpenAI Agents SDK Agent / Runner]
    A <--> M[SQLiteSession: історія діалогу]
    A <--> L[LM Studio: локальна LLM / Chat Completions]
    A --> T[Function tools]
    T --> S[search_knowledge]
    T --> C[calculate: AST]
    T --> F[list_knowledge_sources]
    S --> R[LangChain RedisVectorStore]
    R --> E[MiniLM: query embedding на CPU]
    E --> V[Redis Stack: COSINE / FLAT]
    V --> K[Top-k фрагменти + metadata]
    K --> A
```

Пошуковий інструмент повертає фрагменти. Окремої LLM для переказу retrieval немає. Runner може зробити кілька модельних викликів для інструментів; фінальну відповідь формує цей самий агент.

## 4. Середовище

Наведено виміряні версії. Пакет `langchain` як метапакет не потрібний: використано `langchain-core`, splitters та окремі інтеграції.

In [2]:
environment = read('metadata/environment.json')
display(pd.DataFrame(environment['packages'].items(), columns=['package','version']))
print({k:environment[k] for k in ['python','cuda','gpu','model_id','lm_studio_url']})

                     package       version
0                      torch  2.14.0+cu130
1               transformers        5.17.0
2                     openai        3.17.0
3              openai-agents        0.22.3
4                  langchain           NaN
5             langchain-core         1.6.4
6        langchain-community           NaN
7      langchain-huggingface         1.2.2
8            langchain-redis         0.2.6
9   langchain-text-splitters         1.1.2
10     sentence-transformers         6.1.0
11                     redis         8.1.0
12                   redisvl        0.27.2
13                    httpx2        2.13.0

{'python': '3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]', 'cuda': '13.0', 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'model_id': 'mistralai/ministral-3-3b', 'lm_studio_url': 'http://localhost:1234/v1'}

## 5. База знань

SHA-256 перевіряється за локальними копіями. Оригінальні лабораторні не є runtime-залежностями.

In [3]:
display(pd.DataFrame(validate_corpus())[['source_id','workspace_filename','size_bytes','sha256']])

,source_id,workspace_filename,size_bytes,sha256
0,lab03,lab03_rag_report.md,20169,c0868ad8220f7aa30a65a0e5206c4a4bcddc61731f4a23...
1,lab04,lab04_stable_diffusion_report.md,16033,ed04c0943add4aa9e091bc1da7cd118b07e19ab5da3b3f...
2,lab05,lab05_multimodal_report.md,25125,9c4fce1431dd2cba9c0514fd5941f05783453e37795153...
3,lab06,lab06_agents_report.md,34221,bccc31c3d081b410818d2fbfaa363fd182a8a8db436179...

## 6. Підготовка документів

MarkdownHeaderTextSplitter зберігає розділи, RecursiveCharacterTextSplitter обмежує фрагмент 900 символами з overlap 120. ID залежить від SHA джерела, розділу, нормалізованого тексту й порядкового номера. Короткі завершені секції збережено; окремий фрагмент має лише 74 символи.

In [4]:
chunks = read('metadata/chunks.json')
print({k:v for k,v in chunks.items() if k!='samples'})
display(pd.DataFrame(chunks['samples'])[['source_id','section','text']].head(3))

{'document_count': 4, 'chunk_count': 121, 'chunks_per_source': {'lab03': 32, 'lab04': 22, 'lab05': 29, 'lab06': 38}, 'min_length': 74, 'median_length': 572, 'max_length': 898, 'tiny_under_100': 1}

,source_id,section,text
0,lab03,Лабораторна робота №3. Реалізація RAG-системи ...,# Лабораторна робота №3. Реалізація RAG-систем...
1,lab03,14. LM Studio integration,## 14. LM Studio integration \nНа /v1/models ...
2,lab03,Перевірки реалізації,## Перевірки реалізації \n- `python -m pytest...

## 7. Embeddings

MiniLM на CPU, нормалізовані FLOAT32-вектори. Розмірність перевірено на реальному embedding. Ліміт MiniLM — 256 токенів; український текст токенізується неекономно, тому частина фрагментів обрізається лише для embedding. Повний фрагмент залишається у Redis та результаті інструмента. Це суттєве обмеження цього експерименту.

In [5]:
embedding = read('metadata/embedding.json')
print({k:v for k,v in embedding.items() if k!='token_lengths'})

{'model': 'sentence-transformers/all-MiniLM-L6-v2', 'revision': '1110a243fdf4706b3f48f1d95db1a4f5529b4d41', 'dimension': 384, 'device': 'cpu', 'normalization': True, 'max_seq_length': 256, 'truncated_chunks': 76}

## 8. Redis vector index

Повторний запуск має додати нуль документів. Перевіряються справжній FT.INFO, кількість і схема, а не лише наявність маркера.

In [6]:
settings = Settings()
kb = KnowledgeBase(settings)
index = kb.initialize()
print(index)
assert index['inserted'] == 0
client, settings = await connect(settings)
try:
    assert experiment_fingerprint(settings, kb) == read('runs/batch.json')['fingerprint']
finally:
    await client.close()
print('Поточна конфігурація відповідає збереженій серії.')

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (386 > 256). Running this sequence through the model will result in indexing errors

{'index_name': 'lab07_course_kb_idx', 'key_prefix': 'lab07:kb', 'corpus_fingerprint': '0fc5d62dce3bc6b31df58f245098b3b8817ff40fc11dc9c05bac05df35b4c5d4', 'document_count': 4, 'chunk_count': 121, 'indexed_count': 121, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'embedding_dimension': 384, 'distance_metric': 'COSINE', 'index_algorithm': 'FLAT', 'chunk_size': 900, 'chunk_overlap': 120, 'status': 'reused', 'inserted': 0, 'redis_version': '7.4.7', 'verified_vector': {'identifier': 'embedding', 'attribute': 'embedding', 'type': 'VECTOR', 'algorithm': 'FLAT', 'data_type': 'FLOAT32', 'dim': 384, 'distance_metric': 'COSINE', 'flags': []}}

Поточна конфігурація відповідає збереженій серії.

## 9. Перевірка retrieval

Source Hit@5 означає наявність потрібного звіту серед п’яти сусідів. Не доводить, що знайдено потрібний факт. Невідомий запит не входить у знаменник.

In [7]:
metrics = read('retrieval/metrics.json')
print('Source Hit@5:', metrics['source_hits'], '/', metrics['eligible'])
display(pd.DataFrame(metrics['queries']))
live = kb.search('Which Stable Diffusion model was used in Lab 4?')
display(pd.DataFrame([c.to_dict() for c in live])[['source_id','section','chunk_id','cosine_distance']])

Source Hit@5: 6 / 7

,query_id,hit_at_k,all_sources_hit,expected,retrieved,first_expected_rank,runtime_ms
0,q01,True,True,[lab04],"[lab04, lab05, lab06]",1.0,17.6948
1,q02,True,True,[lab06],[lab06],1.0,14.2881
2,q03,True,True,[lab03],"[lab03, lab06]",1.0,18.2535
3,q04,True,True,[lab04],"[lab04, lab05]",1.0,15.9520
4,q05,True,True,[lab05],"[lab05, lab06]",2.0,18.0984
5,q06,False,False,[lab06],"[lab03, lab04, lab05]",NaN,17.5948
6,q07,True,True,"[lab04, lab05]","[lab03, lab04, lab05]",1.0,14.9280
7,q08,None,None,[],"[lab05, lab06]",NaN,18.1619

,source_id,section,chunk_id,cosine_distance
0,lab04,Джерела,chunk-485e34b872f4250a,0.504884
1,lab05,9. Вхідне зображення,chunk-70830b7bfc138ce1,0.535185
2,lab04,Модель і середовище,chunk-61ffcc82588fbd5f,0.570621
3,lab06,Зауваження до кожної відповіді фінальної серії,chunk-074ea88e1bd963e2,0.621342
4,lab04,Лабораторна робота №4,chunk-a0c61ebe7c32291d,0.658331

## 10. Agent

`tool_choice=auto`, temperature=0, max_turns=10, max_tokens=900. Три функції: `search_knowledge`, `list_knowledge_sources`, `calculate`. Еталони відокремлені у scenarios.json і не передаються Runner. Cloud tracing вимкнено; клієнт дозволяє лише loopback endpoint.

In [8]:
preflight = read('metadata/tool_preflight.json')
print(preflight['user_input'], preflight['tools_used'], preflight['final_answer'])
summary, comparison = summarize(records)
display(summary[['scenario_id','variant','tool_call_count','status']])

Calculate (21 + 7) / 4 using your calculator. ['calculate'] Результат розрахунку **(21 + 7) / 4** дорівнює **7**.

    scenario_id    variant  tool_call_count   status
0          role  assistant                0  SUCCESS
1          lab4  assistant                1  SUCCESS
2          lab4      plain                0  SUCCESS
3          lab3  assistant                1  SUCCESS
4          lab5  assistant                1  SUCCESS
5         cross  assistant                2  SUCCESS
6         cross      plain                0  SUCCESS
7         multi  assistant                3  SUCCESS
8         multi      plain                0  SUCCESS
9        memory  assistant                2  SUCCESS
10       memory  assistant                1  SUCCESS
11    isolation  assistant                0  SUCCESS
12  unsupported  assistant                3  SUCCESS
13  unsupported      plain                0  SUCCESS
14      sources  assistant                1  SUCCESS

## 11. Структурована пам’ять

SQLiteSession зберігає повідомлення й результати функцій між ходами. RAG зберігає зовнішні документи. Це різні види інформації. Кожний незалежний сценарій та baseline мають новий session ID.

In [9]:
display(summary[summary.category.isin(['memory','isolation'])][['scenario_id','session_id','memory','answer_correctness']])

,scenario_id,session_id,memory,answer_correctness
9,memory,experiment_713ff3eff94c_memory,NOT_APPLICABLE,INCORRECT
10,memory,experiment_713ff3eff94c_memory,PASS,PARTIAL
11,isolation,experiment_713ff3eff94c_isolation,PASS,CORRECT

## 12. Простий RAG-запит

In [10]:
r = next(r for r in records if r['scenario_id']=='lab4' and r['agent_variant']=='assistant')
print(r['user_input']); print(r['final_answer']); print('Tools:',r['tools_used'])

Which Stable Diffusion model was used in Lab 4?
В лабораторній роботі **Lab 4** використовувався **Stable Diffusion v1.5**, конкретний ID моделі: `stable-diffusion-v1-5` або еквівалент `runwayml/stable-diffusion-v1-5` **[lab04#chunk-61ffcc82588fbd5f]**.
Tools: ['search_knowledge']

## 13. Cross-document query

In [11]:
r = next(r for r in records if r['scenario_id']=='cross' and r['agent_variant']=='assistant')
print(r['final_answer']); print('Sources:',r['sources_retrieved'])

В лабораторній роботі **Lab 4** використовувався **нейронний текстово-зображеннявий модель Stable Diffusion**, який спеціалізувався на генерації зображень за текстом. Його основна роль полягала в перетворенні опису (prompt) у візуальну картину, виходячи лише з мовних інструкцій.

У **Lab 5** використовувалася **мультимодальна модель LLaVA**, яка об'єднувала зображення та текст. Її основні компоненти включали:
- **SigLIP Vision**: виділяв візуальні ознаки зображень.
- **MLP-проєктор**: переводив ці ознаки у формат, який можна було обробити мовною моделлю (наприклад, Qwen2).
- **Chat template**: інтегрував візуальний вхід у відповідні позиції для генерації текстового опису або розуміння зображення разом із текстом.

Таким чином, модель Lab 4 працювала лише з текстовими наказами і генерувала зображення, тоді як модель Lab 5 **обробляла обох типів даних (зображення та текст) одночасно**, дозволяючи не тільки створювати зображення за текстом, а й аналізувати їх у контексті опису або навпаки.
Sources: ['lab04', 'lab05']

## 14. Multi-step scenario

Нижче лише спостережувані function calls та відповідь. Правильний калькулятор не гарантує правильності отриманих із retrieval операндів.

In [12]:
r = next(r for r in records if r['scenario_id']=='multi' and r['agent_variant']=='assistant')
trace = json.loads((lab/r['trace_path']).read_text(encoding='utf-8'))
display(pd.DataFrame([{'step':e['step'],'tool':e['tool_name'],'arguments':e['arguments']} for e in trace if e['event_type']=='tool_call']))
print(r['final_answer'])

   step              tool                                          arguments
0     2  search_knowledge  {"query":"Lab 4 випродуковано вихідних даних",...
1     3  search_knowledge  {"query":"Lab 5 виконано задач VQA","k":3,"sou...
2     6  search_knowledge  {"query":"Lab 4 кількість генерацій у файлі ge...

Відповідно до індексованих звітів:

- **Lab 4**: У файлі `generations.csv` було записано **13 унікальних генерацій** (цифрові дані про кожне зображення, включаючи різні комбінації seed, промптів і параметрів). Цей факт підтверджується [lab04#chunk-3ac026fae50fcc08].

- **Lab 5**: Про виконання конкретних задач VQA (Visual Question Answering) в звіті не наведено явного числа генерацій. Використане зображення з Lab 4 було лише для візуальної оцінки, але без опису кількості виконаних VQA-задач.

**Не можливо визначити кількість виконаних VQA-генерацій у Lab 5 відповідно до індексованих даних.**

---
*Умовно припустимо, що Lab 4 випродукував більше генерацій за наявних доказів.*

## 15. Memory scenario

Другий запит не повторює назву лабораторної. Окремо наведено той самий follow-up у свіжій сесії.

In [13]:
for r in records:
    if r['scenario_id'] in ['memory','isolation']:
        print(r['session_id'], '\nUser:',r['user_input'],'\nAssistant:',r['final_answer'],'\n')

experiment_713ff3eff94c_memory
User: What model was used in Lab 6?
Assistant: У **Лабораторній роботі №6** не вказано конкретної назви моделі, яка використовувалася для основних завдань. Проте з контексту випливає, що експерименти проводилися з використанням **інструментованих агентів**, які працювали над даними з попередніх лабораторних робіт (Lab 4 і Lab 5).

Основні моменти:
- Моделі для інференсу в цій лабораторній роботі не обговорюються як окремі моделі, а використовувалися **інструменти та агенти** для роботи з даними.
- У відсутності конкретної назви моделі можна припустити, що це було пов'язано з **попередніми експериментами в роботі з генеративними моделями або RAG-системами**, які використовувалися у Lab 4 і Lab 5.

Для точного визначення конкретної моделі потрібно переглянути **Lab 4 і Lab 5** — там, як правило, описуються використані моделі. Якщо це необхідно, я можу провести додатковий пошук у цих лабораторних роботах.

У даному випадку не виявлено прямых відомостей про конкретну модель в **Lab 6**.

experiment_713ff3eff94c_memory
User: What main behavioral weakness was observed with it?
Assistant: Основною **поведінковою слабкістю**, яку спостерігали в цій лабораторній роботі, є:

**Нестабільність та вигадування нереалістичних даних без доступу до інструментів.**
- Без використання дозволених інструментів модель **відмовилася від генерації корисних відповідей**, а в фінальній серії вигадала **неіснуючі CSV-файли, випадкові числа (наприклад, 28 і 32) та невірні дані з таблиць** ([lab06#chunk-5d88f20d503c73f6]).

Це свідчить про **проблему надійності без зовнішніх джерел інформації**, що вимагає додаткового контролю або обмежень.

experiment_713ff3eff94c_isolation
User: What main behavioral weakness was observed with it?
Assistant: Could you clarify which specific system, model, or experiment (e.g., a lab report like **lab03**, **lab04**, etc.) you are referring to? For example:

- Did you mean the behavior in **lab05**?
- Or another context from earlier discussions?

Please specify!

## 16. Unsupported information

In [14]:
r = next(r for r in records if r['scenario_id']=='unsupported' and r['agent_variant']=='assistant')
print(r['user_input']); print(r['final_answer'])

What exact outdoor temperature was recorded when Lab 4 was executed?
У лабораторній роботі **Lab 04** точна зовнішня температура не була прямо зазначена в доступних відомостях. Виявлені лише параметри генерації, такі як кількість кроків та CFG-вага, але без згадки температури повітря.

**Не визначаю.**

## 17. Простий LLM vs RAG + Agent

Чотири однакові запитання, одна модель, system instructions, temperature та token limit, порожня історія. Відрізняється доступ до інструментів. Пряме звертання інструкції до неіснуючих tools у baseline може сприяти вигаданим викликам; це обмеження контрольованого дизайну, а не привід зараховувати їх як справжні.

In [15]:
display(comparison[['scenario_id','plain_correctness','assistant_correctness','tools_used','plain_runtime','assistant_runtime']])
with pd.option_context('display.max_colwidth', 400):
    display(comparison[['scenario_id','plain_answer','assistant_answer']])

,scenario_id,plain_correctness,assistant_correctness,tools_used,plain_runtime,assistant_runtime
0,lab4,PARTIAL,PARTIAL,search_knowledge,6.800,11.342
1,cross,INCORRECT,PARTIAL,search_knowledge → search_knowledge,48.869,49.342
2,multi,INCORRECT,INCORRECT,search_knowledge → search_knowledge → search_k...,12.989,48.400
3,unsupported,INCORRECT,CORRECT,search_knowledge → search_knowledge → search_k...,13.244,19.652

,scenario_id,plain_answer,assistant_answer
0,lab4,"Searching indexed coursework for ""Lab 4"" + ""Stable Diffusion"":\n\n- **Lab 4** (source_id#chunk_id: [lab4_report#1]) explicitly states:\n *""We utilized the Stable Diffusion v1.5 model for image generation tasks.""*\n\nNo other labs mention a different version or variant of Stable Diffusion in this context.\nAnswer: **Stable Diffusion v1.5**.","В лабораторній роботі **Lab 4** використовувався **Stable Diffusion v1.5**, конкретний ID моделі: `stable-diffusion-v1-5` або еквівалент `runwayml/stable-diffusion-v1-5` **[lab04#chunk-61ffcc82588fbd5f]**."
1,cross,"To compare the models from **Lab 4** and **Lab 5**, let’s clarify their contexts first:\n\n- **Lab 4** typically involves a **neural network trained on single-modal data** (e.g., text, images, or audio alone). If this lab used a transformer-based model (common in NLP), it likely focused on:\n - Processing sequential or structured input (e.g., word embeddings, CNN features).\n - Task-specific...","В лабораторній роботі **Lab 4** використовувався **нейронний текстово-зображеннявий модель Stable Diffusion**, який спеціалізувався на генерації зображень за текстом. Його основна роль полягала в перетворенні опису (prompt) у візуальну картину, виходячи лише з мовних інструкцій.\n\nУ **Lab 5** використовувалася **мультимодальна модель LLaVA**, яка об'єднувала зображення та текст. Її основні ко..."
2,multi,"To determine this, let's first clarify what is meant by ""generated outputs"" and ""VQA generations"":\n\n- **Lab 4**: The indexed reports mention a total of **10 unique generations** (e.g., in [source_id#chunk_2]).\n- **Lab 5**: The indexed reports indicate **3 VQA generations** (e.g., in [source_id#chunk_3]).\n\n### Comparison:\n- Lab 4 produced **7 more generations** than Lab 5 ([10 - 3 = 7]).\...","Відповідно до індексованих звітів:\n\n- **Lab 4**: У файлі `generations.csv` було записано **13 унікальних генерацій** (цифрові дані про кожне зображення, включаючи різні комбінації seed, промптів і параметрів). Цей факт підтверджується [lab04#chunk-3ac026fae50fcc08].\n\n- **Lab 5**: Про виконання конкретних задач VQA (Visual Question Answering) в звіті не наведено явного числа генерацій. Вико..."
3,unsupported,"Searching for ""Lab 4"" in indexed reports:\n\n- **Lab 4** (source_id: *L4_2023*) mentions:\n *""Відповідно до звіту про виконання лабораторної роботи №4, зовнішня температура була зафіксована на рівні **+18°C** при проведенні експериментів у кімнаті з відкритим вікном.""*\n\n- **Lab 4** (source_id: *L4_2023_variant*) notes:\n *""За даними логів, зовнішня температура під час виконання лабораторно...","У лабораторній роботі **Lab 04** точна зовнішня температура не була прямо зазначена в доступних відомостях. Виявлені лише параметри генерації, такі як кількість кроків та CFG-вага, але без згадки температури повітря.\n\n**Не визначаю.**"

## 18. Зведення експериментів

SUCCESS — лише завершення Runner. Оцінки фактів і підтримки тверджень отримано ручним переглядом відповідей та відповідних retrieval traces, не LLM-суддею.

In [16]:
display(summary[['scenario_id','variant','answer_correctness','grounding','retrieval','tool_behavior','citation','memory','planning','runtime_seconds']])

,scenario_id,variant,answer_correctness,grounding,retrieval,tool_behavior,citation,memory,planning,runtime_seconds
0,role,assistant,NOT_SCORABLE,GROUNDED,NOT_APPLICABLE,APPROPRIATE,NOT_APPLICABLE,NOT_APPLICABLE,NOT_APPLICABLE,3.005
1,lab4,assistant,PARTIAL,GROUNDED,RELEVANT,APPROPRIATE,PASS,NOT_APPLICABLE,NOT_APPLICABLE,11.342
2,lab4,plain,PARTIAL,UNSUPPORTED,NOT_APPLICABLE,MISSING,FAIL,NOT_APPLICABLE,NOT_APPLICABLE,6.800
3,lab3,assistant,INCORRECT,PARTIAL,RELEVANT,APPROPRIATE,PASS,NOT_APPLICABLE,FAIL,36.806
4,lab5,assistant,INCORRECT,PARTIAL,FAILED,APPROPRIATE,PASS,NOT_APPLICABLE,FAIL,34.491
5,cross,assistant,PARTIAL,PARTIAL,PARTIAL,APPROPRIATE,FAIL,NOT_APPLICABLE,PARTIAL,49.342
6,cross,plain,INCORRECT,UNSUPPORTED,NOT_APPLICABLE,MISSING,FAIL,NOT_APPLICABLE,FAIL,48.869
7,multi,assistant,INCORRECT,PARTIAL,PARTIAL,MISSING,PASS,NOT_APPLICABLE,FAIL,48.400
8,multi,plain,INCORRECT,UNSUPPORTED,NOT_APPLICABLE,MISSING,FAIL,NOT_APPLICABLE,FAIL,12.989
9,memory,assistant,INCORRECT,UNSUPPORTED,FAILED,APPROPRIATE,FAIL,NOT_APPLICABLE,FAIL,40.538
10,memory,assistant,PARTIAL,PARTIAL,RELEVANT,APPROPRIATE,PASS,PASS,PARTIAL,38.881
11,isolation,assistant,CORRECT,GROUNDED,NOT_APPLICABLE,APPROPRIATE,NOT_APPLICABLE,PASS,NOT_APPLICABLE,4.987
12,unsupported,assistant,CORRECT,PARTIAL,NOT_APPLICABLE,UNNECESSARY,FAIL,NOT_APPLICABLE,PARTIAL,19.652
13,unsupported,plain,INCORRECT,UNSUPPORTED,NOT_APPLICABLE,MISSING,FAIL,NOT_APPLICABLE,FAIL,13.244
14,sources,assistant,CORRECT,GROUNDED,NOT_APPLICABLE,APPROPRIATE,NOT_APPLICABLE,NOT_APPLICABLE,NOT_APPLICABLE,9.689

## 19. Помилки та обмеження

Англомовний MiniLM на українських звітах; обрізання embedding-входів; top-k не гарантує потрібного розділу. Lab 6 цитує хибні відповіді попереднього агента — їх не можна приймати за факти. Валідний chunk ID не доводить, що твердження випливає з chunk. Один запуск на питання не оцінює стабільність.

In [17]:
display(summary[['scenario_id','variant','notes']])

    scenario_id    variant                                              notes
0          role  assistant  Коректна розмовна відповідь без tools; стиль н...
1          lab4  assistant  Правильно названо Stable Diffusion v1.5 та leg...
2          lab4      plain  Версію v1.5 вгадано, але пошук, англомовна цит...
3          lab3  assistant  6/7 і неповнота retrieval підтримані. Причину ...
4          lab5  assistant  Retrieval дав лише загальні розділи. Галюцинац...
5         cross  assistant  Знайдено обидва джерела, правильно названо сім...
6         cross      plain  Замість фактичних моделей — припущення про BER...
7         multi  assistant  13 для Lab 4 правильно, але цитований chunk-3a...
8         multi      plain  Вигадано 10 і 3, різницю 7, цитати та докази. ...
9        memory  assistant  Lab 6 явно вказує mistralai/ministral-3-3b; мо...
10       memory  assistant  Історія правильно прив’язує it до Lab 6: sourc...
11    isolation  assistant  Нова сесія запитує уточнення замість успадкува...
12  unsupported  assistant  Не вигадано температуру, повідомлено неможливі...
13  unsupported      plain  Вигадано +18°C, +17.9°C, датчик і два source_i...
14      sources  assistant  Справжній list_knowledge_sources повернув чоти...

## 20. Висновки

Система реально об’єднує локальну LLM, Redis retrieval та агентні функції, але доступ до джерел не усуває хибного синтезу. Остаточні кількості нижче отримано зі збереженої серії.

In [18]:
assistant = summary[summary.variant=='assistant']
print('Завершені запуски:', int((summary.status=='SUCCESS').sum()), '/', len(summary))
print('Оцінки асистента:', assistant.answer_correctness.value_counts().to_dict())
print('Ідентифікатори цитат:', assistant.citation.value_counts().to_dict())
print('Порівнянь із baseline:', len(comparison))

Завершені запуски: 15 / 15
Оцінки асистента: {'INCORRECT': 4, 'PARTIAL': 3, 'CORRECT': 3, 'NOT_SCORABLE': 1}
Ідентифікатори цитат: {'PASS': 5, 'NOT_APPLICABLE': 3, 'FAIL': 3}
Порівнянь із baseline: 4